### PR TITLE
Restructure and update 2020-12-15 agenda

### PR DESCRIPTION
**Pull request by hyperair**
- Membership and finance updates -> Recurring Updates
- Updates from last meeting -> Followup from last meeting

### CODE REVIEW

**Review by rolandturner — COMMENTED** [review]
Apologies, have made approximately the same changes in parallel. I've hand-merged content changes, are you OK with them?

**Comment by dyanawu** [comment]
@rolandturner sticking my nose in while @hyperair is stuck in the hwroom - the changes look fine in substance; I've opened another PR to handle formatting.

**Comment by dyanawu** [comment]
@hyperair close this?

**Review by valentine — APPROVED** [review]

**Comment by valentine** [comment]
As discussed, @rolandturner has rolled in these updates in https://github.com/hackerspacesg/hackerspace.sg/commit/d9bb79757a20201767cd6aa9b76303664c16f75d, https://github.com/hackerspacesg/hackerspace.sg/commit/4cfde06b1c306a0dc6d0e6f2dcafd03fdf6f652e, and https://github.com/hackerspacesg/hackerspace.sg/commit/0649c1600169ff0c6726cbb3e5bc0e0b8e82d479.

**Pull request closed without merging**
