### PR TITLE
Fix/adjust content for ssl

### PR DESCRIPTION
**Pull request by robertsky**

### CODE REVIEW

**Comment by hyperair** [comment]
I'm not sure tabbed indentation is the right thing to use. The other html files use 2 spaces for indentation.

**Comment by robertsky** [comment]
@hyperair changed.

**Comment by chernjie** [comment]
INDENTATIONS!!! **runs around hysterically**

**Comment by robertsky** [comment]
To be frank, I don't care which indentation 'standards' as long as I can 
run the code sanely.

**Comment by robertsky** [comment]
s/run/read

**Comment by rolandturner** [comment]
It was funnier the first time.

- Roland

**Comment by chernjie** [comment]
As long as the indentation is consistent, especially within the same file.

**Comment by hyperair** [comment]
Is there a reason we're still on absolute links with references to scheme and domain, or can we use relative links?

**Comment by chernjie** [comment]
We should use relative links

**Comment by hyperair** [comment]
Any objections to merging?

**Comment by notthetup** [comment]
+1

**Pull request merged**
