### PR TITLE
Replacement parts 3D printing services

### PR DESCRIPTION
**Pull request by chernjie**
### TODO:
- [x] add description
- [ ] add image
- [ ] decide on a pricing structure
- [ ] get approval

### CODE REVIEW

**Comment by hyperair** [comment]
Oi. My CAD-ing services are going to be costly.

**Comment by chernjie** [comment]
okay, we will adjust it. Why don't you make changes in the `spareparts` branch?

**Comment by notthetup** [comment]
:+1:

**Comment by Valentine** [comment]
I don't think people should feel entitled to @hyperair. Unless 3D engineer == @chernjie.

**Comment by chernjie** [comment]
That part is a troll:
`<troll>`
No problem at all! Our printer comes with a 3D engineer, it works most of the time and if it does not, just poke it with the engine stick. Or you could buy him a meal.
`</troll>`

**Comment by chernjie** [comment]
`</troll>`

**Pull request closed without merging**
