### PR TITLE
Added our FB grp

### PR DESCRIPTION
**Pull request by elfgoh**

### CODE REVIEW

**Comment by kaihendry** [comment]
What's the difference between the two again? :confused:

**Comment by elfgoh** [comment]
https://www.facebook.com/notes/facebook/facebook-tips-whats-the-difference-between-a-facebook-page-and-group/324706977130/

**Comment by rolandturner** [comment]
Roughly:

  * The page is HackerspaceSG Pte. Ltd. speaking publicly.
  * The group is the HackerspaceSG community speaking with itself.


- Roland

**Comment by kaihendry** [comment]
Does everyone know this by the URL or something? Perhaps I'm not part of the Facebook generation since I didn't know this or how I'm supposed to interact with these pages. Would prefer we didn't put our community's content into a walled garden.

**Comment by rolandturner** [comment]
(chuckle)

_*We*_ aren't putting it anywhere, our community is... The [somewhat] 
more open Google Group (this list) is also available for use by members 
choosing to do so, a significant minority does.

- Roland

**Pull request merged**
