### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### hackerspacesg/hackerspace.sg now has a Chat Room on Gitter

@notthetup has just created a chat room. You can visit it here: [https://gitter.im/hackerspacesg/hackerspace.sg](https://gitter.im/hackerspacesg/hackerspace.sg?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/hackerspacesg/hackerspace.sg?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by kaihendry** [comment]
Slack, Gitter... all proprietary ways of chatting. We have a IRC channel on Freenode. https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

**Comment by robertsky** [comment]
@notthetup, sorry. I am not going behind this. gitter.im is basically dead for our community. most of our discussions are on issues and as well as facebook/ or irc.

**Comment by notthetup** [comment]
I accidentally clicked on this and it made a PR. I apologies.

**Comment by robertsky** [comment]
:+1:

**Pull request closed without merging**
